version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./odb_data:/data/db

  mongosh:
    image: mongo:latest
    container_name: my-mongosh
    command: mongosh --host mongodb -u admin -p password --authenticationDatabase admin

volumes:
  mongodb_data:
