version: "3"
services:
  event-app-api:
    image: nishani/eventapp-server
    build:
      context: ./event-app-server-container
      dockerfile: Dockerfile
    container_name: event-app-server-container
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    restart: always
